### PR TITLE
Adding Unit Tests and (Slightly) Faster Logical Comparisons

### PR DESCRIPTION
**Pull request by doug-friedman**
This pull request contains the following changes:

- I added an initial batch of unit tests for all exported functions using the testthat library based on the already great example code in the package.
- I changed the use of `mapply` to `.mapply` in `heat.index` as this internal version of the function is _slightly faster_ and you've already performed error/NA checking previously in the function so it should be safe to use.
- When comparing scalars, I changed the logical comparison operators (e.g. `&`) to the associated double logical operator (e.g. `&&`) for a _very slight increase_ in speed. [See Section 8.2.17 in R Inferno for details.](http://www.burns-stat.com/pages/Tutor/R_inferno.pdf)
- I substituted the previous use of `if(length(x[...]) > 0)` with `any(...)` as it is a _slightly faster_ and more direct way of measure the condition.
- I updated the documentation to roxygen 6.0.1 which deleted a few trailing line breaks, but otherwise didn't do anything major.
- I fixed a typo in the example code for `fahrenheit.to.kelvin` where [temperature was misspelled.](https://github.com/geanders/weathermetrics/blob/master/R/temperature_conversions.R#L238)

 
Feel free to take what you prefer and/or make edits!

### CODE REVIEW

**Comment by geanders** [comment]
Thanks so much for making all these improvements. I've pulled them into a `devel` branch to check them all out before merging them into the master (I'm sure there's probably a more elegant way I could have done it than opening a new PR from your fork, but this seemed to work, so there you go).

**Comment by geanders** [comment]
Thanks so much, these are great! I've added you as a contributor in the DESCRIPTION file. Please let me know if you'd rather not be included there and I'll take you out.

**Comment by doug-friedman** [comment]
No problem! I'm happy to help out.

Sure - I'm happy to be recognized as a contributor!


p.s. I have no idea why that last commit broke the Travis CI build

**Comment by geanders** [comment]
Seems to be currently passing. Would you like me to add your email to the DESCRIPTION, too? If so, could you send it?

**Comment by doug-friedman** [comment]
Ok great! 

Sure - you can use doug.nhp at gmail.com.

**Pull request merged**
